# Generated by Django 4.0.3 on 2022-12-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
    ]
