# Generated by Django 4.0.3 on 2022-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text1', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
