# Generated by Django 4.0.3 on 2022-12-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_suggestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='Suggestion',
        ),
    ]
