# Generated by Django 4.0.3 on 2022-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_profile_architect_score_profile_networks_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='operate_score',
            field=models.IntegerField(default=0),
        ),
    ]
